[package]
name = "gyroflow"
version = "0.0.1"
authors = ["Adrian <adrian.eddy@gmail.com>", "Elvin Chen"]
edition = "2021"
build = "build.rs"

[dependencies]
qmetaobject = { version = "*", git = "https://github.com/AdrianEddy/qmetaobject-rs.git", default-features = false, features = ["log"] }
qttypes     = { version = "*", git = "https://github.com/AdrianEddy/qmetaobject-rs.git", default-features = false, features = ["required", "qtquick", "qtquickcontrols2"]}
qml-video-rs = { path = "../qml-video-rs" }
telemetry-parser = { path = "../telemetry-parser" }
#qml-video-rs = { git = "https://github.com/AdrianEddy/qml-video-rs.git" }
#telemetry-parser = { git = "https://github.com/AdrianEddy/telemetry-parser.git" }
ahrs = { git = "https://github.com/jmagnuson/ahrs-rs.git" }

cstr = "*"
cpp = "*"
simd-json = "*"
nalgebra = "0.29"
rayon = "*"
biquad = "*"
fastrand = "*"
lazy_static = "*"
crossbeam-channel = "*"
parking_lot = "*"
bincode = "*"
serde = "*"
crc32fast = "*"
byteorder = "*"
#pyo3 = "*"

akaze = { version = "*", git = "https://github.com/rust-cv/cv.git" }
eight-point = { version = "*", git = "https://github.com/rust-cv/cv.git" }
cv-pinhole = { version = "*", git = "https://github.com/rust-cv/cv.git" }
cv-core = { version = "*", git = "https://github.com/rust-cv/cv.git" }
sample-consensus = "*"
arrsac = "*"
rand_xoshiro = "*"
image = "*"
space = { version = "0.17", features = ["alloc"] }
bitarray = { version = "0.9", features = ["space"] }

walkdir = "*"

opencv = { version = "0.58", features = ["clang-runtime"] }

ffmpeg-next = { version = "4.4.0-next.2", git = "https://github.com/zmwangx/rust-ffmpeg", default-features = false, features = ["codec", "filter", "format", "software-resampling", "software-scaling"] }

wgpu = "*"
bytemuck = "*"
pollster = "*"

ocl = { version = "*", optional = true }

[features]
default = ["opencl"]
opencl = ["ocl"]

[build-dependencies]
cpp_build = "*"
winres = "*"

[[bin]]
name = "gyroflow"
path = "src/gyroflow.rs"

# -------------------------- Android stuff --------------------------

# [lib]
# crate-type = ["cdylib"]
# name = "gyroflow"
# path = "src/gyroflow.rs"

[package.metadata.android]
build_targets = [ "aarch64-linux-android" ]

[package.metadata.android.sdk]
min_sdk_version = 21
target_sdk_version = 30

[[package.metadata.android.uses_permission]]
name = "android.permission.WRITE_EXTERNAL_STORAGE"

# [target.'cfg(target_os = "android")'.dependencies]
# ndk = { version = "*", features = ["trace"] }
# ndk-glue = { version = "*",features = ["logger"] }
