[package]
name = "gyroflow"
version = "1.0.0-rc0"
authors = ["Adrian <adrian.eddy@gmail.com>", "Elvin Chen"]
edition = "2021"
build = "build.rs"

[dependencies]
gyroflow-core = { path = "src/core/", features = ["use-opencl", "use-opencv"], default-features = false }

cstr = "*"
cpp = "*"
serde_json = "*"
bytemuck = "*"
nalgebra = "0.29"

qmetaobject = { version = "*", git = "https://github.com/AdrianEddy/qmetaobject-rs.git", branch = "android_build_fix", default-features = false, features = ["log"] }
qttypes     = { version = "*", git = "https://github.com/AdrianEddy/qmetaobject-rs.git", branch = "android_build_fix", default-features = false, features = ["required", "qtquick", "qtquickcontrols2"]}
qml-video-rs = { git = "https://github.com/AdrianEddy/qml-video-rs.git" }
#qml-video-rs = { path = "../qml-video-rs" }

ffmpeg-next = { version = "4.4.0-next.2", git = "https://github.com/zmwangx/rust-ffmpeg", default-features = false, features = ["codec", "filter", "format", "software-resampling", "software-scaling"] }
lazy_static = "*"
parking_lot = "*"

winapi = "*"
simplelog = "*"
log = "*"

ureq = "2.4"
whoami = "*"

[build-dependencies]
cpp_build = "*"
winres = "*"

[[bin]]
name = "gyroflow"
path = "src/gyroflow.rs"

# -------------------------- Android stuff --------------------------

# [lib]
# crate-type = ["cdylib"]
# name = "gyroflow"
# path = "src/gyroflow.rs"

[package.metadata.android]
build_targets = [ "aarch64-linux-android" ]

[package.metadata.android.sdk]
min_sdk_version = 23
target_sdk_version = 29

[[package.metadata.android.uses_permission]]
name = "android.permission.WRITE_EXTERNAL_STORAGE"

[target.'cfg(target_os = "android")'.dependencies]
# ndk = { version = "*", features = ["trace"] }
# ndk-glue = { version = "*", features = ["logger"] }
ndk-sys = { version = "*" }
