name: Feature Request
description: Propose a new feature to the Gyroflow project.
title: "[Feature request]: "
labels: ["enhancement"]
body:
  - type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Description
      placeholder: Tell us your idea!
    validations:
      required: true