[package]
name = "gyroflow-core"
version = "1.2.0"
authors = ["Adrian <adrian.eddy@gmail.com>", "Elvin Chen"]
edition = "2021"

[lib]
name = "gyroflow_core"
path = "lib.rs"

[dependencies]
#telemetry-parser = { path = "../../../telemetry-parser" }
telemetry-parser = { git = "https://github.com/AdrianEddy/telemetry-parser.git", rev = "c03021e" }
ahrs = { version = "0.5.0", features = ["field_access"] }

#rs-sync = { path = "../../../rs-sync" }
rs-sync = { git = "https://github.com/gyroflow/rs-sync.git", rev = "cf5ee33" }

mimalloc = { version = "0.1.29", default-features = false }
nalgebra = { version = "0.30", features = ["serde-serialize"] }
rayon = "1.5.3"
biquad = "0.4.2"
fastrand = "1.8.0"
lazy_static = "1.4.0"
crossbeam-channel = "0.5.6"
parking_lot = "0.12.1"
bincode = "1.3.3"
serde = "1.0.144"
serde_json = "1.0.85"
crc32fast = "1.3.2"
byteorder = "1.4.3"
line_drawing = "1.0.0"
rand = "0.8.5"
time = { version = "0.3.14", features = ["local-offset"] }
itertools = "0.10.3"
num = "0.4.0"
num-traits = "0.2.15"
base91 = "0.1.0"
bitflags = "1.3.2"
enum_dispatch = "0.3.8"
win_dbg_logger = "*"

simple-easing = "1.0.0"

dyn-clone = "1.0.9"

akaze = { version = "*", git = "https://github.com/rust-cv/cv.git", rev = "511024f" }
eight-point = { version = "*", git = "https://github.com/rust-cv/cv.git", rev = "511024f" }
cv-pinhole = { version = "*", git = "https://github.com/rust-cv/cv.git", rev = "511024f" }
cv-core = { version = "*", git = "https://github.com/rust-cv/cv.git", rev = "511024f" }
sample-consensus = "1.0.2"
arrsac = "0.10.0"
rand_xoshiro = "0.6.0"
image = "0.23"
space = { version = "0.17", features = ["alloc"] }
bitarray = { version = "0.9", features = ["space"] }
enterpolation = "0.1.1"

opencv = { version = "0.67", optional = true }

wgpu = "0.13"
bytemuck = "1.12.1"

pollster = "0.2.5"
futures-intrusive = "0.4.0"
flate2 = "1.0.24"
walkdir = "2.3.2"

log = "0.4.17"

ocl = { version = "0.19.4", optional = true }

#cpp = "0.5.6"

rustfft = "6.0.1"
#[build-dependencies]
#cpp_build = "0.5.6"

[features]
default = []
use-opencl = ["ocl"]
use-opencv = ["opencv"]

[profile.deploy]
inherits = "release"
lto = true
codegen-units = 1

[target.'cfg(target_os = "android")'.dependencies]
include_dir = { version = "0.7.2", features = ["glob"] }
